---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---

## 網站資料爬取
```{r}
#這是R Code Chunk
library(rvest) ##第一次使用要先安裝 install.packages("rvest")
pttmovie<-"https://www.ptt.cc/bbs/movie/index.html"

pttdata<-c()
for(n in 1:8){
  pttContent<-read_html(pttmovie)
  post_title <- pttContent %>% html_nodes(".title") %>% html_text()
  post_pushnum<- pttContent %>% html_nodes(".nrec") %>% html_text()
  post_author<- pttContent %>% html_nodes(".author") %>% html_text()
  
  pttmovie_posts <- data.frame(title = post_title, author=post_author, pushnumber=post_pushnum)
  pttdata<-rbind(pttdata,pttmovie_posts)
  
  pttpre<-read_html(pttmovie)%>% html_nodes(".btn-group-paging a:nth_child(2)") %>% html_attr("href")
  pttmovie<-paste0("https://www.ptt.cc",pttpre)
}
##read_html
##html_nodes
##html_text
```

## 爬蟲結果呈現
```{r}
#這是R Code Chunk
knitr::kable(
  pttdata[c("title","author","pushnumber")]) ##請將iris取代為上個步驟中產生的爬蟲資料資料框
```

## 解釋爬蟲結果 
```{r}
str(pttdata)
table(pttdata$author)
```
總共有145篇文章,
iam168888888最多發文


```{r}
#這是R Code Chunk
```

解釋解釋解釋解釋

我發現鄉民會在pttmovie版透過一些訊息請大家幫忙尋找電影名稱

